// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// KpointsColumns holds the columns for the "kpoints" table.
	KpointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "token_pair_id", Type: field.TypeUint32},
		{Name: "k_point_type", Type: field.TypeString, Nullable: true, Default: "KPointTypeUnknown"},
		{Name: "open", Type: field.TypeFloat64},
		{Name: "high", Type: field.TypeFloat64},
		{Name: "low", Type: field.TypeFloat64},
		{Name: "close", Type: field.TypeFloat64},
		{Name: "start_time", Type: field.TypeUint32},
		{Name: "end_time", Type: field.TypeUint32},
	}
	// KpointsTable holds the schema information for the "kpoints" table.
	KpointsTable = &schema.Table{
		Name:       "kpoints",
		Columns:    KpointsColumns,
		PrimaryKey: []*schema.Column{KpointsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "kpoint_token_pair_id_k_point_type_end_time",
				Unique:  false,
				Columns: []*schema.Column{KpointsColumns[4], KpointsColumns[5], KpointsColumns[11]},
			},
			{
				Name:    "kpoint_end_time",
				Unique:  false,
				Columns: []*schema.Column{KpointsColumns[11]},
			},
		},
	}
	// KpricesColumns holds the columns for the "kprices" table.
	KpricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "token_pair_id", Type: field.TypeUint32},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "timestamp", Type: field.TypeUint32},
	}
	// KpricesTable holds the schema information for the "kprices" table.
	KpricesTable = &schema.Table{
		Name:       "kprices",
		Columns:    KpricesColumns,
		PrimaryKey: []*schema.Column{KpricesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "kprice_timestamp",
				Unique:  false,
				Columns: []*schema.Column{KpricesColumns[6]},
			},
			{
				Name:    "kprice_token_pair_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{KpricesColumns[4], KpricesColumns[6]},
			},
		},
	}
	// TokensColumns holds the columns for the "tokens" table.
	TokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "address", Type: field.TypeString},
		{Name: "site", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString},
		{Name: "symbol", Type: field.TypeString},
	}
	// TokensTable holds the schema information for the "tokens" table.
	TokensTable = &schema.Table{
		Name:       "tokens",
		Columns:    TokensColumns,
		PrimaryKey: []*schema.Column{TokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "token_address",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[4]},
			},
			{
				Name:    "token_symbol",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[8]},
			},
		},
	}
	// TokenPairsColumns holds the columns for the "token_pairs" table.
	TokenPairsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "pool_id", Type: field.TypeUint64},
		{Name: "token_zero_id", Type: field.TypeUint32},
		{Name: "token_one_id", Type: field.TypeUint32},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// TokenPairsTable holds the schema information for the "token_pairs" table.
	TokenPairsTable = &schema.Table{
		Name:       "token_pairs",
		Columns:    TokenPairsColumns,
		PrimaryKey: []*schema.Column{TokenPairsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tokenpair_pool_id",
				Unique:  false,
				Columns: []*schema.Column{TokenPairsColumns[4]},
			},
			{
				Name:    "tokenpair_token_zero_id_token_one_id",
				Unique:  true,
				Columns: []*schema.Column{TokenPairsColumns[5], TokenPairsColumns[6]},
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "pool_id", Type: field.TypeUint64},
		{Name: "transaction_id", Type: field.TypeUint64},
		{Name: "transaction_type", Type: field.TypeString},
		{Name: "amount_zero_in", Type: field.TypeFloat64},
		{Name: "amount_one_in", Type: field.TypeFloat64},
		{Name: "amount_zero_out", Type: field.TypeFloat64},
		{Name: "amount_one_out", Type: field.TypeFloat64},
		{Name: "timestamp", Type: field.TypeUint32},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "transaction_timestamp",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[11]},
			},
			{
				Name:    "transaction_transaction_id",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[5]},
			},
			{
				Name:    "transaction_pool_id_timestamp_transaction_id",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[4], TransactionsColumns[11], TransactionsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		KpointsTable,
		KpricesTable,
		TokensTable,
		TokenPairsTable,
		TransactionsTable,
	}
)

func init() {
}
