// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// KPoint is the predicate function for kpoint builders.
type KPoint func(*sql.Selector)

// KPrice is the predicate function for kprice builders.
type KPrice func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// TokenPair is the predicate function for tokenpair builders.
type TokenPair func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)
