apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webui-template-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: webui-template
    k8s.kuboard.cn/workload: webui-template
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-http-redirect-https-testing@kubernetescrd,
      kube-system-common-headers@kubernetescrd

spec:
  rules:
    - host: vue-template.npool.top
      http: &http_ruless
        paths:
          - path: /
            backend:
              serviceName: webui-template
              servicePort: 80
    - host: vue-template.xpool.top
      http: *http_rules
    - host: www.vue-template.npool.top
      http: *http_rules
    - host: www.vue-template.xpool.top
      http: *http_rules
