apiVersion: apps/v1
kind: Deployment
metadata:
  name: kline-service
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kline-service
  template:
    metadata:
      labels:
        app: kline-service
    spec:
      containers:
        - name: kline-service
          image: DOCKER_REGISTRY/linera/kline-service:latest
          imagePullPolicy: Always
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password-secret
                  key: rootpassword
            - name: ENV_SWAP_CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: kline-service-environment
                  key: environment.swap_chain_id
            - name: ENV_SWAP_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: kline-service-environment
                  key: environment.swap_app_id
            - name: ENV_SWAP_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: kline-service-environment
                  key: environment.swap_server_addr
            - name: BRANCH_NAME
              valueFrom:
                configMapKeyRef:
                  name: kline-service-environment
                  key: environment.branch_name
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kline-service
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50870
      targetPort: 50870
    - name: grpc
      port: 50871
      targetPort: 50871
  selector:
    app: kline-service
