pipeline {
  agent any
  stages {
    stage('Clone') {
      steps {
        git(url: scm.userRemoteConfigs[0].url, branch: '$BRANCH_NAME', changelog: true, credentialsId: 'KK-github-key', poll: true)
      }
    }

    stage('Compile') {
      when {
        expression { BUILD_TARGET == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          set +e
          revlist=`git rev-list --tags --max-count=1`
          rc=$?
          set -e
          if [ 0 -eq $rc ] && [ x"$revlist" != x ]; then
            tag=`git tag -l | sort -V | tail -n1`
            major=`echo $tag | awk -F '.' '{ print $1 }'`
            minor=`echo $tag | awk -F '.' '{ print $2 }'`
            patch=`echo $tag | awk -F '.' '{ print $3 }'`
            patch=$(( $patch + $patch % 2 + 1 ))
            tag=$major.$minor.$patch
            sed -ri "s#\\\"version(.*)#\\\"version\\\": \\\"$tag\\\",#" package.json
          fi
        '''.stripIndent())


        sh(returnStdout: false, script: '''
          cd webui
          export ENV_USE_DOMAIN=$ENV_USE_DOMAIN
          export ENV_API_SCHEMA=$ENV_API_SCHEMA
          export erc20_2_bid=$ENV_ERC20_BYTECODE_ID
          export swap_creation_chain=$ENV_SWAP_CREATION_CHAIN_ID
          export swap_creation_owner=$ENV_SWAP_CREATION_OWNER
          export swap_appid=$ENV_SWAP_APP_ID
          export erc20_2_appid=$ENV_WLINERA_APP_ID
          export ams_creation_chain=$ENV_AMS_CREATION_CHAIN_ID
          export ams_appid=$ENV_AMS_APP_ID
          export blob_gateway_creation_chain_id=$ENV_BLOB_CREATION_CHAIN_ID
          export blob_gateway_app_id=$ENV_BLOB_APP_ID

          sed -i "s/erc20BytecodeId: .*/erc20BytecodeId: '$erc20_2_bid',/g" src/mystore/host/index.ts
          sed -i "s/swapCreationChainId: .*/swapCreationChainId: '$swap_creation_chain',/g" src/mystore/host/index.ts
          sed -i "s/swapCreationOwner: .*/swapCreationOwner: '$swap_creation_owner',/g" src/mystore/host/index.ts
          sed -i "s/swapApplicationId: .*/swapApplicationId: '$swap_appid',/g" src/mystore/host/index.ts
          sed -i "s/wlineraApplicationId: .*/wlineraApplicationId: '$erc20_2_appid',/g" src/mystore/host/index.ts
          sed -i "s/amsCreationChainId: .*/amsCreationChainId: '$ams_creation_chain',/g" src/mystore/host/index.ts
          sed -i "s/amsApplicationId: .*/amsApplicationId: '$ams_appid',/g" src/mystore/host/index.ts
          sed -i "s/blobGatewayCreationChainId: .*/blobGatewayCreationChainId: '$blob_gateway_creation_chain_id',/g" src/mystore/host/index.ts
          sed -i "s/blobGatewayApplicationId: .*/blobGatewayApplicationId: '$blob_gateway_app_id'/g" src/mystore/host/index.ts

          set +e
          PATH=/usr/local/bin:$PATH:./node_modules/@quasar/app/bin command quasar
          rc=$?
          set -e
          if [ ! $rc -eq 0 ]; then
            n v20
            PATH=/usr/local/bin:$PATH npm install --global --registry https://registry.npm.taobao.org yarn
            PATH=/usr/local/bin:$PATH yarn add global quasar-cli@latest
          fi
          yarn
          yarn build
        '''.stripIndent())
      }
    }

    stage('Generate docker image for feature') {
      when {
        expression { BUILD_TARGET == 'true' }
        expression { BRANCH_NAME != 'master' }
      }
      steps {
        sh(returnStdout: false, script: '''
          cd webui
          feature_name=`echo $BRANCH_NAME | awk -F '/' '{ print $2 }'`
          sed -i "s#NGINX1.20_DOCKER_REGISTRY_URL#$NGINX_DOCKER_REGISTRY_URL#g" Dockerfile
          docker build -t $DOCKER_REGISTRY/linera/kline-webui:$feature_name .
        '''.stripIndent())
      }
    }

    stage('Generate docker image for development') {
      when {
        expression { BUILD_TARGET == 'true' }
        expression { BRANCH_NAME == 'master' }
      }
      steps {
        sh(returnStdout: false, script: '''
          cd webui
          sed -i "s#NGINX1.20_DOCKER_REGISTRY_URL#$NGINX_DOCKER_REGISTRY_URL#g" Dockerfile
          docker build -t $DOCKER_REGISTRY/linera/kline-webui:latest .
        '''.stripIndent())
      }
    }

    stage('Tag patch') {
      when {
        expression { TAG_PATCH == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          set +e
          revlist=`git rev-list --tags --max-count=1`
          rc=$?
          set -e
          if [ 0 -eq $rc ] && [ x"$revlist" != x ]; then
            tag=`git tag -l | sort -V | tail -n1`
            major=`echo $tag | awk -F '.' '{ print $1 }'`
            minor=`echo $tag | awk -F '.' '{ print $2 }'`
            patch=`echo $tag | awk -F '.' '{ print $3 }'`
            case $TAG_FOR in
              testing)
                patch=$(( $patch + $patch % 2 + 1 ))
                ;;
              production)
                patch=$(( $patch + 1 ))
                git reset --hard
                git checkout $tag
                ;;
            esac
            tag=$major.$minor.$patch
          else
            tag=0.1.1
          fi
          sed -ri "s#\\\"version(.*)#\\\"version\\\": \\\"$tag\\\",#" package.json
          set +e
          git add package.json
          git commit -m "Bump version to $tag"
          set -e
          git tag -a $tag -m "Bump version to $tag"
        '''.stripIndent())

        withCredentials([gitUsernamePassword(credentialsId: 'KK-github-key', gitToolName: 'git-tool')]) {
          sh 'git push --tag'
        }
      }
    }

    stage('Tag minor') {
      when {
        expression { TAG_MINOR == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          set +e
          revlist=`git rev-list --tags --max-count=1`
          rc=$?
          set -e
          if [ 0 -eq $rc ] && [ x"$revlist" != x ]; then
            tag=`git tag -l | sort -V | tail -n1`
            major=`echo $tag | awk -F '.' '{ print $1 }'`
            minor=`echo $tag | awk -F '.' '{ print $2 }'`
            patch=`echo $tag | awk -F '.' '{ print $3 }'`
            minor=$(( $minor + 1 ))
            patch=1
            tag=$major.$minor.$patch
          else
            tag=0.1.1
          fi
          sed -ri "s#\\\"version(.*)#\\\"version\\\": \\\"$tag\\\",#" package.json
          set +e
          git add package.json
          git commit -m "Bump version to $tag"
          set -e
          git tag -a $tag -m "Bump version to $tag"
        '''.stripIndent())

        withCredentials([gitUsernamePassword(credentialsId: 'KK-github-key', gitToolName: 'git-tool')]) {
          sh 'git push --tag'
        }
      }
    }

    stage('Tag major') {
      when {
        expression { TAG_MAJOR == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          set +e
          revlist=`git rev-list --tags --max-count=1`
          rc=$?
          set -e
          if [ 0 -eq $rc ] && [ x"$revlist" != x ]; then
            tag=`git tag -l | sort -V | tail -n1`
            major=`echo $tag | awk -F '.' '{ print $1 }'`
            minor=`echo $tag | awk -F '.' '{ print $2 }'`
            patch=`echo $tag | awk -F '.' '{ print $3 }'`
            major=$(( $major + 1 ))
            minor=0
            patch=1
            tag=$major.$minor.$patch
          else
            tag=0.1.1
          fi
          sed -ri "s#\\\"version(.*)#\\\"version\\\": \\\"$tag\\\",#" package.json
          set +e
          git add package.json
          git commit -m "Bump version to $tag"
          set -e
          git tag -a $tag -m "Bump version to $tag"
        '''.stripIndent())

        withCredentials([gitUsernamePassword(credentialsId: 'KK-github-key', gitToolName: 'git-tool')]) {
          sh 'git push --tag'
        }
      }
    }

    stage('Generate docker image for testing or production') {
      when {
        expression { BUILD_TARGET == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          cd webui
          tag=`git tag -l | sort -V | tail -n1`
          git reset --hard
          git checkout $tag
          export ENV_USE_DOMAIN=$ENV_USE_DOMAIN
          export ENV_API_SCHEMA=$ENV_API_SCHEMA
          export erc20_2_bid=$ENV_ERC20_BYTECODE_ID
          export swap_creation_chain=$ENV_SWAP_CREATION_CHAIN_ID
          export swap_creation_owner=$ENV_SWAP_CREATION_OWNER
          export swap_appid=$ENV_SWAP_APP_ID
          export erc20_2_appid=$ENV_WLINERA_APP_ID
          export ams_creation_chain=$ENV_AMS_CREATION_CHAIN_ID
          export ams_appid=$ENV_AMS_APP_ID
          export blob_gateway_creation_chain_id=$ENV_BLOB_CREATION_CHAIN_ID
          export blob_gateway_app_id=$ENV_BLOB_APP_ID

          sed -i "s/erc20BytecodeId: .*/erc20BytecodeId: '$erc20_2_bid',/g" src/mystore/host/index.ts
          sed -i "s/swapCreationChainId: .*/swapCreationChainId: '$swap_creation_chain',/g" src/mystore/host/index.ts
          sed -i "s/swapCreationOwner: .*/swapCreationOwner: '$swap_creation_owner',/g" src/mystore/host/index.ts
          sed -i "s/swapApplicationId: .*/swapApplicationId: '$swap_appid',/g" src/mystore/host/index.ts
          sed -i "s/wlineraApplicationId: .*/wlineraApplicationId: '$erc20_2_appid',/g" src/mystore/host/index.ts
          sed -i "s/amsCreationChainId: .*/amsCreationChainId: '$ams_creation_chain',/g" src/mystore/host/index.ts
          sed -i "s/amsApplicationId: .*/amsApplicationId: '$ams_appid',/g" src/mystore/host/index.ts
          sed -i "s/blobGatewayCreationChainId: .*/blobGatewayCreationChainId: '$blob_gateway_creation_chain_id',/g" src/mystore/host/index.ts
          sed -i "s/blobGatewayApplicationId: .*/blobGatewayApplicationId: '$blob_gateway_app_id'/g" src/mystore/host/index.ts

          set +e
          PATH=/usr/local/bin:$PATH:./node_modules/@quasar/app/bin command quasar
          rc=$?
          set -e
          if [ ! $rc -eq 0 ]; then
            n v20
            PATH=/usr/local/bin:$PATH npm install --global --registry https://registry.npm.taobao.org yarn
            PATH=/usr/local/bin:$PATH yarn add global quasar-cli@latest
          fi
          yarn
          yarn build
          sed -i "s#NGINX1.20_DOCKER_REGISTRY_URL#$NGINX_DOCKER_REGISTRY_URL#g" Dockerfile
          docker build -t $DOCKER_REGISTRY/linera/kline-webui:$tag .
        '''.stripIndent())
      }
    }

    stage('Release docker image for feature') {
      when {
        expression { RELEASE_TARGET == 'true' }
        expression { BRANCH_NAME != 'master' }
      }
      steps {
        sh(returnStdout: false, script: '''
          feature_name=`echo $BRANCH_NAME | awk -F '/' '{ print $2 }'`
          set +e
          docker images | grep kline-webui | grep $feature_name
          rc=$?
          set -e
          if [ 0 -eq $rc ]; then
            docker push $DOCKER_REGISTRY/entropypool/kline-webui:$feature_name
          fi
          images=`docker images | grep entropypool | grep kline-webui | grep none | awk '{ print $3 }'`
          for image in $images; do
            docker rmi $image -f
          done
        '''.stripIndent())
      }
    }

    stage('Release docker image for development') {
      when {
        expression { RELEASE_TARGET == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          set +e
          docker images | grep kline-webui | grep latest
          rc=$?
          set -e
          if [ 0 -eq $rc ]; then
            docker push $DOCKER_REGISTRY/entropypool/kline-webui:latest
          fi
          images=`docker images | grep entropypool | grep kline-webui | grep none | awk '{ print $3 }'`
          for image in $images; do
            docker rmi $image -f
          done
        '''.stripIndent())
      }
    }

    stage('Release docker image for testing') {
      when {
        expression { RELEASE_TARGET == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          tag=`git tag -l | sort -V | tail -n1`

          set +e
          docker images | grep kline-webui | grep $tag
          rc=$?
          set -e
          if [ 0 -eq $rc ]; then
            docker push $DOCKER_REGISTRY/entropypool/kline-webui:$tag
          fi
        '''.stripIndent())
      }
    }

    stage('Release docker image for production') {
      when {
        expression { RELEASE_TARGET == 'true' }
      }
      steps {
        sh(returnStdout: false, script: '''
          tag=`git tag -l | sort -V | tail -n1`

          major=`echo $tag | awk -F '.' '{ print $1 }'`
          minor=`echo $tag | awk -F '.' '{ print $2 }'`
          patch=`echo $tag | awk -F '.' '{ print $3 }'`

          patch=$(( $patch - $patch % 2 ))
          tag=$major.$minor.$patch

          set +e
          docker images | grep kline-webui | grep $tag
          rc=$?
          set -e
          if [ 0 -eq $rc ]; then
            docker push $DOCKER_REGISTRY/entropypool/kline-webui:$tag
          fi
        '''.stripIndent())
      }
    }

    stage('Deploy for feature') {
      when {
        expression { DEPLOY_TARGET == 'true' }
        expression { BRANCH_NAME != 'master' }
      }
      steps {
        sh(returnStdout: false, script: '''
          feature_name=`echo $BRANCH_NAME | awk -F '/' '{ print $2 }'`
          sed -i "s/kline-webui:latest/kline-webui:$feature_name/g" webui/k8s/01-kline-webui.yaml.yaml
          sed -i "s/DOCKER_REGISTRY/$DOCKER_REGISTRY/g" webui/k8s/01-kline-webui.yaml.yaml
          kubectl apply -k k8s
        '''.stripIndent())
      }
    }

    stage('Deploy for development') {
      when {
        expression { DEPLOY_TARGET == 'true' }
        expression { TARGET_ENV ==~ /.*development.*/ }
        expression { BRANCH_NAME == 'master' }
      }
      steps {
        sh '''
          sed -i "s/DOCKER_REGISTRY/$DOCKER_REGISTRY/g" webui/k8s/01-kline-webui.yaml.yaml
          kubectl apply -k webui/k8s
        '''
      }
    }

    stage('Deploy for testing') {
      when {
        expression { DEPLOY_TARGET == 'true' }
        expression { TARGET_ENV ==~ /.*testing.*/ }
        expression { BRANCH_NAME == 'master' }
      }
      steps {
        sh(returnStdout: false, script: '''
          tag=`git tag -l | sort -V | tail -n1`

          git reset --hard
          git checkout $tag
          sed -i "s/kline-webui:latest/kline-webui:$tag/g" webui/k8s/01-kline-webui.yaml.yaml
          sed -i "s/DOCKER_REGISTRY/$DOCKER_REGISTRY/g" webui/k8s/01-kline-webui.yaml.yaml
          kubectl apply -k webui/k8s
        '''.stripIndent())
      }
    }

    stage('Deploy for production') {
      when {
        expression { DEPLOY_TARGET == 'true' }
        expression { TARGET_ENV ==~ /.*production.*/ }
      }
      steps {
        sh(returnStdout: false, script: '''
          tag=`git tag -l | sort -V | tail -n1`

          major=`echo $tag | awk -F '.' '{ print $1 }'`
          minor=`echo $tag | awk -F '.' '{ print $2 }'`
          patch=`echo $tag | awk -F '.' '{ print $3 }'`
          patch=$(( $patch - $patch % 2 ))
          tag=$major.$minor.$patch

          git reset --hard
          git checkout $tag
          sed -i "s/kline-webui:latest/kline-webui:$tag/g" webui/k8s/01-kline-webui.yaml.yaml
          sed -i "s/DOCKER_REGISTRY/$DOCKER_REGISTRY/g" webui/k8s/01-kline-webui.yaml.yaml
          kubectl apply -k webui/k8s
        '''.stripIndent())
      }
    }

    stage('Post') {
      steps {
        // Assemble vet and lint info.
        // warnings parserConfigurations: [
        //   [pattern: 'govet.txt', parserName: 'Go Vet'],
        //   [pattern: 'golint.txt', parserName: 'Go Lint']
        // ]

        // sh 'go2xunit -fail -input gotest.txt -output gotest.xml'
        // junit "gotest.xml"
        sh 'echo Posting'
      }
    }
  }
  post('Report') {
    fixed {
      script {
        sh(script: 'bash $JENKINS_HOME/wechat-templates/send_wxmsg.sh fixed')
     }
      script {
        // env.ForEmailPlugin = env.WORKSPACE
        emailext attachmentsPattern: 'TestResults\\*.trx',
        body: '${FILE,path="$JENKINS_HOME/email-templates/success_email_tmp.html"}',
        mimeType: 'text/html',
        subject: currentBuild.currentResult + " : " + env.JOB_NAME,
        to: '$DEFAULT_RECIPIENTS'
      }
     }
    success {
      script {
        sh(script: 'bash $JENKINS_HOME/wechat-templates/send_wxmsg.sh successful')
     }
      script {
        // env.ForEmailPlugin = env.WORKSPACE
        emailext attachmentsPattern: 'TestResults\\*.trx',
        body: '${FILE,path="$JENKINS_HOME/email-templates/success_email_tmp.html"}',
        mimeType: 'text/html',
        subject: currentBuild.currentResult + " : " + env.JOB_NAME,
        to: '$DEFAULT_RECIPIENTS'
      }
     }
    failure {
      script {
        sh(script: 'bash $JENKINS_HOME/wechat-templates/send_wxmsg.sh failure')
     }
      script {
        // env.ForEmailPlugin = env.WORKSPACE
        emailext attachmentsPattern: 'TestResults\\*.trx',
        body: '${FILE,path="$JENKINS_HOME/email-templates/fail_email_tmp.html"}',
        mimeType: 'text/html',
        subject: currentBuild.currentResult + " : " + env.JOB_NAME,
        to: '$DEFAULT_RECIPIENTS'
      }
     }
    aborted {
      script {
        sh(script: 'bash $JENKINS_HOME/wechat-templates/send_wxmsg.sh aborted')
     }
      script {
        // env.ForEmailPlugin = env.WORKSPACE
        emailext attachmentsPattern: 'TestResults\\*.trx',
        body: '${FILE,path="$JENKINS_HOME/email-templates/fail_email_tmp.html"}',
        mimeType: 'text/html',
        subject: currentBuild.currentResult + " : " + env.JOB_NAME,
        to: '$DEFAULT_RECIPIENTS'
      }
     }
  }
}
